name: Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: false
          activate-environment: mlflow-env
          environment-file: MLProject/conda.yaml
          auto-update-conda: true
          conda-solver: classic

      - name: Run MLflow Project
        working-directory: MLProject
        run: conda run -n mlflow-env mlflow run . -P data_path=data_preprocessed.csv

      - name: Upload model artifact
        uses: actions/upload-artifact@v4
        with:
          name: model
          path: mlruns  # Upload full MLflow tracking dir

  docker:
    needs: train
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: false
          activate-environment: mlflow-env
          environment-file: MLProject/conda.yaml
          auto-update-conda: true
          conda-solver: classic

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Download model artifact
        uses: actions/download-artifact@v4
        with:
          name: model
          path: mlruns

      - name: Debug artifact path
        run: |
          echo "Listing mlruns directory:"
          ls -R mlruns

      - name: Build and Push Docker Image
        shell: bash -l {0}  # 🧠 activate conda shell
        run: |
          LATEST_RUN=$(find mlruns/0 -type d -name artifacts | sed 's|/artifacts||' | head -1)
          echo "Using model path: $LATEST_RUN/artifacts/model"
          mlflow models build-docker -m $LATEST_RUN/artifacts/model -n salary-model
          docker tag salary-model ${{ secrets.DOCKER_USERNAME }}/income-classification:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/income-classification:latest
