name: Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: false
          activate-environment: mlflow-env
          environment-file: MLProject/conda.yaml
          auto-update-conda: true
          conda-solver: classic

      - name: Install mlflow
        shell: bash -l {0}
        run: |
          conda activate mlflow-env
          pip install mlflow

      - name: Run MLflow Project
        shell: bash -l {0}
        working-directory: MLProject
        run: |
          conda activate mlflow-env
          mlflow run . -P data_path=data_preprocessed.csv

      - name: Upload model artifact
        uses: actions/upload-artifact@v4
        with:
          name: model
          path: MLProject/outputs/mlflow-model/

  docker:
    needs: train
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: false
          activate-environment: mlflow-env
          environment-file: MLProject/conda.yaml
          auto-update-conda: true
          conda-solver: classic

      - name: Install mlflow
        shell: bash -l {0}
        run: |
          conda activate mlflow-env
          pip install mlflow

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Download model artifact
        uses: actions/download-artifact@v4
        with:
          name: model
          path: MLProject/outputs/mlflow-model/

      - name: Build and Push Docker Image
        shell: bash -l {0}
        run: |
          conda activate mlflow-env
          mlflow models build-docker -m MLProject/outputs/mlflow-model -n salary-model
          docker tag salary-model ${{ secrets.DOCKER_USERNAME }}/income-classification:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/income-classification:latest
